# Generated by Django 2.2.7 on 2020-04-05 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SerieTv', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='serie',
            name='imagePath',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='stagione',
            name='numero',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='episodio',
            name='imagePath',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='episodio',
            name='numero',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='episodio',
            name='videoPath',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='serie',
            name='title',
            field=models.TextField(null=True),
        ),
    ]
