# Generated by Django 2.2.7 on 2020-04-05 17:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Film', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='film',
            old_name='name',
            new_name='title',
        ),
    ]
