# Generated by Django 2.2.7 on 2020-04-05 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Film', '0002_auto_20200405_1935'),
    ]

    operations = [
        migrations.AddField(
            model_name='film',
            name='cachePath',
            field=models.TextField(null=True),
        ),
    ]
