# Generated by Django 2.2.7 on 2020-04-05 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Film', '0004_auto_20200405_1950'),
    ]

    operations = [
        migrations.AddField(
            model_name='film',
            name='lastWatch',
            field=models.DateTimeField(null=True),
        ),
    ]
