# Generated by Django 2.2.7 on 2020-04-05 19:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Film', '0005_film_lastwatch'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='film',
            name='duration',
        ),
    ]
