# Generated by Django 2.2.7 on 2020-04-05 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Film', '0006_remove_film_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='film',
            name='video',
            field=models.FileField(null=True, upload_to='Static/upload/'),
        ),
    ]
