# Generated by Django 2.2.7 on 2020-04-05 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Film', '0007_film_video'),
    ]

    operations = [
        migrations.CreateModel(
            name='FileUpload',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(null=True, upload_to='Static/upload/')),
            ],
        ),
        migrations.RemoveField(
            model_name='film',
            name='video',
        ),
    ]
