# Generated by Django 2.2.7 on 2020-04-06 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Film', '0010_film_duration'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FileUpload',
        ),
        migrations.AddField(
            model_name='film',
            name='file',
            field=models.FileField(null=True, upload_to='Static/upload'),
        ),
    ]
